[project]
name = "dir-scout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "redis>=6.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
